# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Projects
    url: projects/
    weight: 15
  - name: Tags
    url: tags/
    weight: 20
  # - name: Uses
  #   url: uses/
  #   weight: 30
  # - name: Uses Again
  #   url: uses/
  #   weight: 40
  # - name: Broken
  #   url: broken/
  #   weight: 50
